---
- name: Solr | Remove downloaded tarball and sources
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ solr_workspace }}/{{ solr_url|basename }}"
    - "{{ solr_workspace }}/{{ (solr_url|basename|splitext)[0] }}"

- name: Solr | Remove docs, if not needed
  file:
    path: "{{ solr_install_path }}/docs"
    state: absent
  when: solr_cleanup_full

- name: Remove example dir, if not needed
  file:
    path: "{{ solr_install_path }}/example"
    state: absent
  when: solr_cleanup_full
