---
- name: Solr | Remove existing SOLR_HEAP configuration
  lineinfile:
    dest: "{{ solr_config_file }}"
    regexp: "^SOLR_HEAP"
    state: absent
  notify: restart solr

- name: Solr | Apply configuration changes
  lineinfile:
    dest: "{{ solr_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^.?SOLR_JAVA_MEM="
      line: 'SOLR_JAVA_MEM="-Xms{{ solr_xms }} -Xmx{{ solr_xmx }}"'
    - regexp: "^SOLR_PORT="
      line: 'SOLR_PORT="{{ solr_port }}"'
    - regexp: "^.?SOLR_TIMEZONE="
      line: 'SOLR_TIMEZONE="{{ solr_timezone }}"'
  notify: restart solr

- block:
  - name: Solr | Ensure lib directory exists
    file:
      path: "{{ solr_home }}/data/lib"
      state: directory
      owner: "{{ solr_user }}"
      group: "{{ solr_user }}"

  - name: Solr | Copy library jars in to place
    copy:
      src: "{{ item }}"
      remote_src: yes
      dest: "{{ solr_home }}/data/lib/"
      owner: "{{ solr_user }}"
      group: "{{ solr_user }}"
      mode: 0644
    with_items: "{{ solr_extra_libs }}"
    notify: restart solr

  when: solr_extra_libs|length
