---
- name: Solr | Ensure group exists
  group: "name={{ solr_user }} state=present"

- name: Solr | Ensure user exists
  user:
    name: "{{ solr_user }}"
    group: "{{ solr_user }}"
    state: present
